### PR TITLE
Update page-load.js - Adding some request options

### PR DESCRIPTION
**Pull request by DrJest**
Added an option to change request behaviour, allowing to add custom request headers, change request method and progress/abort callbacks
Had to change this to deal with Wordpress's admin-ajax which only accepts POST requests, maybe someone else could find it useful

### CODE REVIEW

**Comment by desandro** [comment]
Thanks for opening this PR. I could see how this kind of feature would be useful. 
**Add a 👍  reaction** to this issue if you would like to see this feature added. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by ret394** [comment]
it would be more useful if merged in some day. this vote to show issue weight stuff is another dumb way to make decisions. 

>  Wordpress's admin-ajax which only accepts POST requests

is that correct way to behave?

**Comment by calinrada** [comment]
Is the maintainer dead ?

**Comment by desandro** [comment]
[Infinite Scroll v4](https://infinite-scroll.com) has been released. Infinite Scroll v4 adds a new option, [`fetchOptions`](https://infinite-scroll.com/options.html#fetchoptions), which allows you to set method, headers, CORS mode, and other fetch options.

``` js
fetchOptions: {
  mode: 'cors',
  cache: 'no-cache',
  credentials: 'same-origin',
  headers: {
    'X-Session-Id': '33vscths658h7996d324rqft1s',
  },
},
```

Thank you for your original contribution. While I did not merge it in, your effort did help me decide to support the feature.

**Pull request closed without merging**
