### PR TITLE
Supported 204 No content

### PR DESCRIPTION
**Pull request by icetee**
Server can send 204 HTTP code. This indicates there is no more content.
https://httpstatuses.com/204

### CODE REVIEW

**Comment by desandro** [comment]
Thank you for this contribution. This seems very straight forward. Before I merge, I'll have to update documentation to mention this new feature. I'll keep this open until then.

**Comment by zackkatz** [comment]
This would be great to have merged. Thanks, @icetee!

**Comment by Enalmada** [comment]
I was just going to open a ticket asking for this same thing.  It seems like infinite-scroll is crashing on 204 right now which makes this a very desirable merge.  Thanks @desandro!

**Comment by desandro** [comment]
This PR has been merged and will be included in the next release.

**Pull request merged**
